
run_good:
	APP_START_TIMEOUT=5s \
 	APP_STOP_TIMEOUT=5s \
 	APP_ECHO_HANDLER_RESPONSE_TIMEOUT=2s \
	APP_SERVER_HOST=localhost \
	APP_SERVER_PORT=8080 \
	go run main.go

run_bad:
	APP_START_TIMEOUT=5s \
	APP_STOP_TIMEOUT=5s \
	APP_ECHO_HANDLER_RESPONSE_TIMEOUT=2s \
	APP_SERVER_HOST=localhost \
	APP_SERVER_PORT=9080 \
	go run main.go
